# frozen_string_literal: true

source "https://rubygems.org"

# Specify your gem's dependencies in dotenvcrypt.gemspec
gemspec

# For development, use local core gem
gem "dotenvcrypt-core", path: "../core"

group :development do
  gem "rake", "~> 13.0"
  gem "minitest", "~> 5.0"
end
